import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import ReactQueryProvider from '@/lib/query-provider';

const poppins = Poppins({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-poppins',
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
	title: 'Biuro Pielgrzymkowo - Turystyczne Credo',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.ico',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pl'>
			<body
				className={`${poppins.className} bg-main-background overflow-x-hidden`}
			>
				<ReactQueryProvider>
					<Header />
					<main>{children}</main>
					<Footer />
				</ReactQueryProvider>
			</body>
		</html>
	);
}
