import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Biuro Pielgrzymkowo - Turystyczne Credo',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.ico',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pl'>
			<body
				className={`${inter.className} bg-main-background overflow-x-hidden`}
			>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
